-- MySQL Script generated by MySQL Workbench
-- Wed Jan 27 15:48:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurant_booking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant_booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant_booking` DEFAULT CHARACTER SET latin1 ;
USE `restaurant_booking` ;

-- -----------------------------------------------------
-- Table `restaurant_booking`.`restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurant_booking`.`restaurant` ;

CREATE TABLE IF NOT EXISTS `restaurant_booking`.`restaurant` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `rating` DOUBLE NOT NULL,
  `is_open` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `restaurant_booking`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurant_booking`.`schedule` ;

CREATE TABLE IF NOT EXISTS `restaurant_booking`.`schedule` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `restaurantId` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `slots_left` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Schedule_Restaurant_idx` (`restaurantId` ASC) VISIBLE,
  CONSTRAINT `FK_Schedule_Restaurant`
    FOREIGN KEY (`restaurantId`)
    REFERENCES `restaurant_booking`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `restaurant_booking`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurant_booking`.`user` ;

CREATE TABLE IF NOT EXISTS `restaurant_booking`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_admin` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `restaurant_booking`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `restaurant_booking`.`booking` ;

CREATE TABLE IF NOT EXISTS `restaurant_booking`.`booking` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `booking_date` DATETIME NOT NULL,
  `userId` INT(11) NOT NULL,
  `scheduleId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Booking_User_idx` (`userId` ASC) VISIBLE,
  INDEX `FK_Booking_Schedule_idx` (`scheduleId` ASC) VISIBLE,
  CONSTRAINT `FK_Booking_Schedule`
    FOREIGN KEY (`scheduleId`)
    REFERENCES `restaurant_booking`.`schedule` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Booking_User`
    FOREIGN KEY (`userId`)
    REFERENCES `restaurant_booking`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
